### PR TITLE
client.say + CSE

### PR DESCRIPTION
**Pull request by mike-bailey**
Similar to the recent slack-aws work PR, except also that CSE is mandated (no wide search) so I removed that test case since it doesn't work anyways.

### CODE REVIEW

**Comment by mike-bailey** [comment]
My CSE thing was wrong, but the changes should still be made since you need a paid plan and I doubt everyone has that.

**Comment by mike-bailey** [comment]
No idea what Travis's issue is but it checksums fine on my system.

**Comment by dblock** [comment]
Thanks. But you cannot delete the spec that checks that the code actually does a search. Put it back and I can help with fixing it if you can't figure it out.

**Comment by dblock** [comment]
The faraday thing seems transient, I am sure it will fix itself or someone will fix it somewhere soon :)

**Comment by mike-bailey** [comment]
I'll put it back but I'm fairly certain it's on account of I don't have a site search key, because it's a paid key. Figured I'd remove it just because contributors may not have a paid key to pass this case.

**Comment by mike-bailey** [comment]
The Faraday thing may not be so transient, pretty sure I got the error yesterday on an Ubuntu box, forgot the details.
EDIT: looks like it's an open issue
https://github.com/lostisland/faraday_middleware/issues/152

**Comment by mike-bailey** [comment]
Alright, everything should be good now - not sure why the test case is passing now but I'll take it.

**Comment by dblock** [comment]
VCR records the session and fakes the request on a subsequent run. They are passing because of the previous recording.

**Comment by dblock** [comment]
Merged, thx.

**Pull request merged**
